from .extensions import db
from datetime import date

class Sponsor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(40), unique=True, nullable=False)
    password = db.Column(db.String(30), nullable=False)
    industry = db.Column(db.String(30), nullable=False)
    ongoing_campaigns = db.Column(db.Integer, default=0)
    successful_campaigns = db.Column(db.Integer, default=0)
    phone_number = db.Column(db.Integer, unique=True, nullable=False)
    picture = db.Column(db.String(200), nullable=True)
    is_flagged = db.Column(db.Boolean, default=False)
    campaigns = db.relationship('Campaign', backref='sponsor', lazy=True)
    ad_requests = db.relationship('AdRequest', backref='sponsor', lazy=True)

class Influencer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(40), unique=True, nullable=False)
    password = db.Column(db.String(30), nullable=False)
    niche = db.Column(db.String(30), nullable=False)
    phone_number = db.Column(db.Integer, unique=True, nullable=False)
    dob = db.Column(db.Date, nullable=False)
    gender = db.Column(db.String(10), nullable=True)
    ongoing_campaigns = db.Column(db.Integer, default=0)
    successful_campaigns = db.Column(db.Integer, default=0)
    picture = db.Column(db.String(200), nullable=True)
    is_flagged = db.Column(db.Boolean, default=False)
    ad_requests = db.relationship('AdRequest', backref='influencer', lazy=True)
    campaigns = db.relationship('Campaign', backref='influencer', lazy=True)

class Campaign(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    sponsor_id = db.Column(db.Integer, db.ForeignKey('sponsor.id'), nullable=False )
    influencer_id = db.Column(db.Integer, db.ForeignKey('influencer.id'), nullable=False ,default=0)
    description = db.Column(db.String(500), nullable=False)
    posts = db.Column(db.Integer, default=0)
    total_posts = db.Column(db.Integer, default=0)
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)
    budget = db.Column(db.Integer, nullable=False)
    visibility = db.Column(db.String(500), default='Private')
    goal = db.Column(db.String(200), nullable=False)
    picture = db.Column(db.String(200), nullable=True)
    ad_requests = db.relationship('AdRequest', backref='campaign', lazy=True)

class AdRequest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    campaign_id = db.Column(db.Integer, db.ForeignKey('campaign.id'), nullable=False)
    sponsor_id = db.Column(db.Integer, db.ForeignKey('sponsor.id'), nullable=False)
    influencer_id = db.Column(db.Integer, db.ForeignKey('influencer.id'), nullable=False)
    message = db.Column(db.String(300), nullable=False)
    payment = db.Column(db.Integer, nullable=False)
    posts = db.Column(db.Integer, nullable=False)
    initiated_for = db.Column(db.String(300), nullable=False)
    initiator = db.Column(db.String(300), nullable=False)
    date = db.Column(db.Date, default=date.today)
